Use TICKET_BOOKING_SYSTEM;
CREATE TABLE [Venue]
(
    [Venue_id] VARCHAR(50),
    [Venue_name] VARCHAR(50),
    [address] VARCHAR(50),
    PRIMARY KEY ([Venue_id])
);


CREATE TABLE [EVENT]
(
    [EVENT_ID] VARCHAR(50),
    [EVENT_NAME] VARCHAR(50),
    [EVENT_DATE] DATE,
    [EVENT_TIME] TIME,
    [VENUE_ID] VARCHAR(50),
    [TOTAL_SEATS] INT,
    [AVAILABLE_SEATS] INT,
    [TICKET_PRICE] DECIMAL,
    [EVENT_TYPE] VARCHAR(50),
    [BOOKING_ID] VARCHAR(50)
        PRIMARY KEY ([EVENT_ID]),
    Foreign Key ([VENUE_ID]) references VENUE([VENUE_ID]),
    --Foreign Key ([BOOKING_ID]) references BOOKING([BOOKING_ID]),
);

CREATE TABLE [CUSTOMER]
(
    [CUSTOMER_ID] VARCHAR(50),
    [CUSTOMER_NAME] VARCHAR(50),
    [EMAIL] VARCHAR(50),
    [PHONE_NUMBER] VARCHAR(50),
    [BOOKING_ID] VARCHAR(50),
    PRIMARY KEY ([CUSTOMER_ID]),
    --Foreign Key ([BOOKING_ID]) references BOOKING([BOOKING_ID]),
);


CREATE TABLE [BOOKING]
(
    [BOOKING_ID] VARCHAR(50),
    [CUSTOMER_ID] VARCHAR(50),
    [EVENT_ID] VARCHAR(50),
    [NUM_TICKETS] INT,
    [TOTAL_COST] DECIMAL,
    [BOOKING_DATE] DATE
        PRIMARY KEY ([BOOKING_ID]),
    Foreign Key ([CUSTOMER_ID]) references CUSTOMER([CUSTOMER_ID]),
    Foreign Key ([EVENT_ID]) references EVENT([EVENT_ID]),
);

ALTER TABLE EVENT
   ADD FOREIGN KEY (BOOKING_ID)
      REFERENCES BOOKING (BOOKING_ID);

ALTER TABLE CUSTOMER
   ADD FOREIGN KEY (BOOKING_ID)
      REFERENCES BOOKING (BOOKING_ID);